trigger: none

pool:
  vmImage: macos-11

steps:
- checkout: self
  persistCredentials: true

- script: |
    echo "$secret_message" >> messages.txt
  displayName: 'Show secret variable'
  env:
    secret_message: $(SECRET_MESSAGE)

- script: |
    git add messages.txt
    git commit -m "Update messages.txt [skip ci]"
    git push
  displayName: 'Update messages'
