name: Call Azure

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: 'https://dev.azure.com/cantrellkalalau/cantrellkalalau'
          azure-pipeline-name: 'klcantrell.test-azurepipelines-github-action'
          azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'
          # azure-pipeline-variables: '{"message": "HI!"}' # this is an ignored parameter for now https://github.com/Azure/pipelines/issues/40
